In [13]:
import pandas as pd 
import seaborn as sb
import numpy as np
import matplotlib.pyplot as plt
import scipy as stats
from sklearn import preprocessing
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation

In [14]:
df = pd.read_csv('BitcoinHeistData.csv')

In [15]:
df

address  year  day  length     weight  \
0         111K8kZAEnJg245r2cM6y9zgJGHZtJPy6  2017   11      18   0.008333   
1        1123pJv8jzeFQaCV4w644pzQJzVWay2zcA  2016  132      44   0.000244   
2        112536im7hy6wtKbpH1qYDWtTyMRAcA2p7  2016  246       0   1.000000   
3        1126eDRw2wqSkWosjTCre8cjjQW8sSeWH7  2016  322      72   0.003906   
4        1129TSjKtx65E35GiUo4AYVeyo48twbrGX  2016  238     144   0.072848   
...                                     ...   ...  ...     ...        ...   
2916692  12D3trgho1vJ4mGtWBRPyHdMJK96TRYSry  2018  330       0   0.111111   
2916693  1P7PputTcVkhXBmXBvSD9MJ3UYPsiou1u2  2018  330       0   1.000000   
2916694  1KYiKJEfdJtap9QX2v9BXJMpz2SfU4pgZw  2018  330       2  12.000000   
2916695  15iPUJsRNZQZHmZZVwmQ63srsmughCXV4a  2018  330       0   0.500000   
2916696  3LFFBxp15h9KSFtaw55np8eP5fv6kdK17e  2018  330     144   0.073972   

         count  looped  neighbors        income            label  
0            1       0          2  1.000500e+08  princetonCerber  
1            1       0          1  1.000000e+08   princetonLocky  
2            1       0          2  2.000000e+08  princetonCerber  
3            1       0          2  7.120000e+07  princetonCerber  
4          456       0          1  2.000000e+08   princetonLocky  
...        ...     ...        ...           ...              ...  
2916692      1       0          1  1.255809e+09            white  
2916693      1       0          1  4.409699e+07            white  
2916694      6       6         35  2.398267e+09            white  
2916695      1       0          1  1.780427e+08            white  
2916696   6800       0          2  1.123500e+08            white  

[2916697 rows x 10 columns]

In [16]:
# df.info()
df.isna().sum().sum()

0

No nan values found

In [17]:
#still for precaution
df.dropna()

address  year  day  length     weight  \
0         111K8kZAEnJg245r2cM6y9zgJGHZtJPy6  2017   11      18   0.008333   
1        1123pJv8jzeFQaCV4w644pzQJzVWay2zcA  2016  132      44   0.000244   
2        112536im7hy6wtKbpH1qYDWtTyMRAcA2p7  2016  246       0   1.000000   
3        1126eDRw2wqSkWosjTCre8cjjQW8sSeWH7  2016  322      72   0.003906   
4        1129TSjKtx65E35GiUo4AYVeyo48twbrGX  2016  238     144   0.072848   
...                                     ...   ...  ...     ...        ...   
2916692  12D3trgho1vJ4mGtWBRPyHdMJK96TRYSry  2018  330       0   0.111111   
2916693  1P7PputTcVkhXBmXBvSD9MJ3UYPsiou1u2  2018  330       0   1.000000   
2916694  1KYiKJEfdJtap9QX2v9BXJMpz2SfU4pgZw  2018  330       2  12.000000   
2916695  15iPUJsRNZQZHmZZVwmQ63srsmughCXV4a  2018  330       0   0.500000   
2916696  3LFFBxp15h9KSFtaw55np8eP5fv6kdK17e  2018  330     144   0.073972   

         count  looped  neighbors        income            label  
0            1       0          2  1.000500e+08  princetonCerber  
1            1       0          1  1.000000e+08   princetonLocky  
2            1       0          2  2.000000e+08  princetonCerber  
3            1       0          2  7.120000e+07  princetonCerber  
4          456       0          1  2.000000e+08   princetonLocky  
...        ...     ...        ...           ...              ...  
2916692      1       0          1  1.255809e+09            white  
2916693      1       0          1  4.409699e+07            white  
2916694      6       6         35  2.398267e+09            white  
2916695      1       0          1  1.780427e+08            white  
2916696   6800       0          2  1.123500e+08            white  

[2916697 rows x 10 columns]

In [18]:
n = len(pd.unique(df['address']))
n

2631095

In [19]:
df=df.drop(['address'],axis=1)
#dropped address column because two many unique values will only 
#contribute to computation complexity when the address feature is not significant
df

year  day  length     weight  count  looped  neighbors        income  \
0        2017   11      18   0.008333      1       0          2  1.000500e+08   
1        2016  132      44   0.000244      1       0          1  1.000000e+08   
2        2016  246       0   1.000000      1       0          2  2.000000e+08   
3        2016  322      72   0.003906      1       0          2  7.120000e+07   
4        2016  238     144   0.072848    456       0          1  2.000000e+08   
...       ...  ...     ...        ...    ...     ...        ...           ...   
2916692  2018  330       0   0.111111      1       0          1  1.255809e+09   
2916693  2018  330       0   1.000000      1       0          1  4.409699e+07   
2916694  2018  330       2  12.000000      6       6         35  2.398267e+09   
2916695  2018  330       0   0.500000      1       0          1  1.780427e+08   
2916696  2018  330     144   0.073972   6800       0          2  1.123500e+08   

                   label  
0        princetonCerber  
1         princetonLocky  
2        princetonCerber  
3        princetonCerber  
4         princetonLocky  
...                  ...  
2916692            white  
2916693            white  
2916694            white  
2916695            white  
2916696            white  

[2916697 rows x 9 columns]

### Part 1

In [20]:
target=['label']
features=df.columns[:-1]
features

Index(['year', 'day', 'length', 'weight', 'count', 'looped', 'neighbors',
       'income'],
      dtype='object')

In [21]:
X=df[features]
print(X)
Y=df[target]
print(Y)

         year  day  length     weight  count  looped  neighbors        income
0        2017   11      18   0.008333      1       0          2  1.000500e+08
1        2016  132      44   0.000244      1       0          1  1.000000e+08
2        2016  246       0   1.000000      1       0          2  2.000000e+08
3        2016  322      72   0.003906      1       0          2  7.120000e+07
4        2016  238     144   0.072848    456       0          1  2.000000e+08
...       ...  ...     ...        ...    ...     ...        ...           ...
2916692  2018  330       0   0.111111      1       0          1  1.255809e+09
2916693  2018  330       0   1.000000      1       0          1  4.409699e+07
2916694  2018  330       2  12.000000      6       6         35  2.398267e+09
2916695  2018  330       0   0.500000      1       0          1  1.780427e+08
2916696  2018  330     144   0.073972   6800       0          2  1.123500e+08

[2916697 rows x 8 columns]
                   label
0        pr

In [22]:
#encoding the target column 
label_encoder = preprocessing.LabelEncoder()
df['label']= label_encoder.fit_transform(df['label'])


In [23]:
df = df.sample(frac=1)
train_size = 0.70
test_size = 0.15
valid_size=0.15

train_index = int(len(df)*train_size)

df_train = df[0:train_index]
df_rem = df[train_index:]

valid_index = int(len(df)*valid_size)

df_valid = df[train_index:train_index+valid_index]
df_test = df[train_index+valid_index:]

X_train, y_train = df_train.drop(columns='label'), df_train['label']
X_valid, y_valid = df_valid.drop(columns='label'), df_valid['label']
X_test, y_test = df_test.drop(columns='label'), df_test['label']
trees_both=[]

In [24]:
# Create Decision Tree classifer object with entropy
accuracy_entropy=[]
depth=[4,8,10,15,20]
for i in depth:
    clf = DecisionTreeClassifier(criterion="entropy", max_depth=i)
    # Train Decision Tree Classifer
    clf = clf.fit(X_train,y_train)
    #Predict the response for test dataset
    y_pred = clf.predict(X_valid)
    print("Accuracy for depth",i,":",metrics.accuracy_score(y_valid, y_pred))
    accuracy_entropy.append(metrics.accuracy_score(y_valid, y_pred))

Accuracy for depth 4 : 0.9855155610005851
Accuracy for depth 8 : 0.9857807014335869
Accuracy for depth 10 : 0.9870424041837331
Accuracy for depth 15 : 0.9879201104447045
Accuracy for depth 20 : 0.9860984128145114


In [25]:
# Create Decision Tree classifer object with gini index
accuracy_gini=[]
for i in depth:
    clf = DecisionTreeClassifier(criterion="gini", max_depth=i)
    # Train Decision Tree Classifer
    clf = clf.fit(X_train,y_train)
    #Predict the response for test dataset
    y_pred = clf.predict(X_valid)
    print("Accuracy for depth",i,":",metrics.accuracy_score(y_valid, y_pred))
    accuracy_gini.append(metrics.accuracy_score(y_valid, y_pred))

Accuracy for depth 4 : 0.9855155610005851
Accuracy for depth 8 : 0.9862081260971328
Accuracy for depth 10 : 0.9867864065242832
Accuracy for depth 15 : 0.9878286827091867
Accuracy for depth 20 : 0.9863589818607372


In [26]:
for i in range(len(depth)):
    print("Accuracy for depth",depth[i],"with entropy:",accuracy_entropy[i])
    print("Accuracy for depth",depth[i],"with gini:",accuracy_gini[i])

Accuracy for depth 4 with entropy: 0.9855155610005851
Accuracy for depth 4 with gini: 0.9855155610005851
Accuracy for depth 8 with entropy: 0.9857807014335869
Accuracy for depth 8 with gini: 0.9862081260971328
Accuracy for depth 10 with entropy: 0.9870424041837331
Accuracy for depth 10 with gini: 0.9867864065242832
Accuracy for depth 15 with entropy: 0.9879201104447045
Accuracy for depth 15 with gini: 0.9878286827091867
Accuracy for depth 20 with entropy: 0.9860984128145114
Accuracy for depth 20 with gini: 0.9863589818607372


The best accuracy for the ginni and entropy creteria is best with the max depth of 15

In [27]:
clf = DecisionTreeClassifier(criterion="entropy", max_depth=15)
# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)
#Predict the response for test dataset
y_pred = clf.predict(X_valid)
print("Accuracy for depth",15,":",metrics.accuracy_score(y_valid, y_pred))
accuracy_entropy.append(metrics.accuracy_score(y_valid, y_pred))

Accuracy for depth 15 : 0.9878766822703335


In [28]:

clf = DecisionTreeClassifier(criterion="gini", max_depth=15)
# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)
#Predict the response for test dataset
y_pred = clf.predict(X_test)
print("Accuracy for depth",15,":",metrics.accuracy_score(y_test, y_pred))
# accuracy_gini.append(metrics.accuracy_score(y_valid, y_pred))

Accuracy for depth 15 : 0.9881921619360649


### Part 2
Ensembling is a method to combine multiple not-so-good models to get
a better performing model. Create 100 different decision stumps (max depth 3).
For each stump, train it on randomly selected 50% of the training data, i.e., select
data for each stump separately. Now, predict the test samples’ labels by taking
a majority vote of the output of the stumps. How is the performance affected as
compared to parts (a)

In [29]:
def train_trees(X, Y, num_trees):
    indices = [i for i in range(X.shape[0])]

    # Here, note that we have set max_depth = 3 which
    # makes all the classifiers weak
    trees = [DecisionTreeClassifier(max_depth=3) for _ in range(num_trees)]
    for tree in trees:
        # Selecting n random samples with replacement from training set
        random_indices = np.random.choice(indices, X.shape[0])
        print(random_indices)
        # Bootstrap training data
        X_bootstrap= X.iloc[random_indices]
        Y_bootstrap= Y.iloc[random_indices]
        # X_bootstrap = X[random_indices]
        # Y_bootstrap = Y[random_indices]

        tree.fit(X_bootstrap, Y_bootstrap)
    
    return trees

In [30]:
def predict(X, trees):
    predictions = []
    for tree in trees:
        Y_pred = tree.predict(X)
        predictions.append(Y_pred)
    
    predictions = np.array(predictions)

    # Aggregating all predictions to get final prediction
    # Since this is a classification problem, we use mode
    # i.e. the prediction that occurs the maximum number
    # of times. In case of regression problem, we use mean
    prediction = np.array(stats.stats.mode(predictions))
    return prediction[0, 0, :]

In [31]:
# NUM_RANDOM_FEATURES = 
# put 50% of data from the dataset df into x train and y train  
df = df.sample(frac=1)
train_size = 0.50
# test_size = 0.50

train_index = int(len(df)*train_size)

df_train = df[0:train_index]
df_rem = df[train_index:]

# df_test = df[train_index+valid_index:]

X_train, y_train = df_train.drop(columns='label'), df_train['label']
# X_valid, y_valid = df_valid.drop(columns='label'), df_valid['label']
X_test, y_test = df_rem.drop(columns='label'), df_rem['label']



In [32]:
# accuracies = []
trees = train_trees(X_train, y_train, 100)
prediction = predict(X_test, trees)
# accuracy = (prediction == y_test).sum() / prediction.shape[0]
# accuracies.append(accuracy)

# plt.plot(accuracies)

[ 487038 1007506  563817 ... 1368765 1150143   97461]
[1407639   39934  202282 ...   92420  423861  476474]
[ 790485 1354128  382393 ...  244555  422526  909608]
[ 300892  159636  801999 ... 1300258 1271287 1307805]
[ 812440 1316672  967794 ... 1256109  171250 1216143]
[380163 598884 413676 ... 458473 324453 856961]
[ 519269  548718 1156057 ...  183524   86952  243393]
[507258 233889 106903 ... 805654 701789 505699]
[ 546497  658392  698508 ...  786156 1368889  217902]
[1244210  739834 1293874 ...  594322  737519  569317]
[1038793  910238  966858 ...   81740  819588  153268]
[1240813 1078517  307703 ...  938405  924306  337887]
[492803 674715 517661 ... 408470 492369 776330]
[ 664939  735775  963678 ...    8297 1247053  459211]
[ 51247 636122 261997 ... 755708 521831 792985]
[993794 286242 565969 ... 659036 765881 641545]
[569821 769165 680852 ... 735125 779739 959945]
[ 605713 1404682  976885 ...  740845  944513  477987]
[  97579 1294435  467748 ...   45698 1303553  756960]
[ 664463  

In [33]:
accuracy = (prediction == y_test).sum() / prediction.shape[0]
accuracy


0.985858666204043

In [34]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score

# Create adaboost classifer object
abc = AdaBoostClassifier(n_estimators=100, learning_rate=1, random_state=42)

# Train Adaboost Classifer
model1 = abc.fit(X_train, y_train)

#Predict the response for test dataset
y_pred_abc = model1.predict(X_test)


In [35]:
accuracy = (y_pred_abc == y_test).sum() / y_pred_abc.shape[0]
accuracy

0.9858230094442414